### ISSUE TITLE
Precompute time

### ISSUE THREAD

**Issue by Narabzad** [jingtaozhan/RepBERT-Index#2]
Hello,

Thank you for your good work.
How much do you think it takes approximately to precompute all the memmaps for msmarco collection on one RTX-2080- 8GB gpu?  It seems it takes several days... I want to make sure I am on the correct path.

**Comment by jingtaozhan** [comment]
Thank you for your attention to our work.
I have a RTX-1080Ti gpu and it costs about 12 hours.
It's very important to dynamically pad the input ids to the max length of the batch, as [dataset.py](https://github.com/jingtaozhan/RepBERT-Index/blob/master/dataset.py) did. Padding all the passages to 512 tokens is very unnecessary and inefficient. 
I also recommend you to read our [recent work](https://arxiv.org/abs/2010.10469).

**Comment by Narabzad** [comment]
Thank you for your quick response.
I am using your code to precompute the dense representation of documents so I assume it already pads the inputs dynamically. Is that correct?

**Comment by jingtaozhan** [comment]
Yes, that's correct.
